# -*- coding: utf-8 -*-
"""CF_NeuMF_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p1F579oxJbY6WLPgz2tT7-PjdXqpG4gx

# CF_NeuMF_v4 — Improved NeuMF on MovieLens 100K

**Key improvements over v3:**
1. **BPR pairwise loss** — directly optimises ranking order (better than BCE for top-K metrics)
2. **Popularity-weighted negative sampling** — negatives ∝ freq^0.75, harder than uniform
3. **Dynamic Negative Sampling (DNS)** — after warmup, pick the hardest negative from dns_k candidates per batch
4. **Larger architecture** — emb_dim 64→128, MLP (256,128,64)→(512,256,128)
5. **Pre-trained initialisation** — GMF+MLP branches warm-started before fine-tuning
6. **50 training epochs** (was 30)
"""

!pip install -q torch anthropic

import os, io, json, zipfile, random, warnings
import requests
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from collections import defaultdict
warnings.filterwarnings('ignore')

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device : {DEVICE}")
print(f"PyTorch: {torch.__version__}")

"""## 1. Data"""

def load_movielens_100k(cache_dir: str = 'ml-100k') -> tuple:
    """Download and parse MovieLens 100K."""
    url = 'https://files.grouplens.org/datasets/movielens/ml-100k.zip'
    if not os.path.exists(cache_dir):
        print('Downloading MovieLens 100K...')
        r = requests.get(url, timeout=60); r.raise_for_status()
        zipfile.ZipFile(io.BytesIO(r.content)).extractall('.')
        print('Done.')

    ratings = pd.read_csv(
        f'{cache_dir}/u.data', sep='\t',
        names=['user_id', 'item_id', 'rating', 'timestamp']
    )
    genre_cols = [
        'unknown', 'action', 'adventure', 'animation', 'childrens', 'comedy',
        'crime', 'documentary', 'drama', 'fantasy', 'film_noir', 'horror',
        'musical', 'mystery', 'romance', 'sci_fi', 'thriller', 'war', 'western'
    ]
    items_df = pd.read_csv(
        f'{cache_dir}/u.item', sep='|', encoding='latin-1', header=None,
        usecols=list(range(24)),
        names=['item_id', 'title', 'release_date', 'video_date', 'imdb_url'] + genre_cols
    )[['item_id', 'title'] + genre_cols]
    return ratings, items_df


ratings, items_df = load_movielens_100k()
print(f"Ratings : {len(ratings):,}")
print(f"Users   : {ratings.user_id.nunique()}")
print(f"Items   : {ratings.item_id.nunique()}")
print(f"\nRating distribution:")
print(ratings['rating'].value_counts().sort_index().to_string())

def build_implicit_dataset(
    ratings: pd.DataFrame,
    pos_threshold: int = 4,
    min_interactions: int = 5
) -> tuple:
    """
    Binarise ratings >= pos_threshold.
    Split: per-user leave-one-out (last interaction → test).
    """
    pos = ratings[ratings['rating'] >= pos_threshold].copy()

    user_ids = sorted(pos['user_id'].unique())
    item_ids = sorted(pos['item_id'].unique())
    user2idx = {u: i for i, u in enumerate(user_ids)}
    item2idx = {v: i for i, v in enumerate(item_ids)}
    pos['user'] = pos['user_id'].map(user2idx)
    pos['item'] = pos['item_id'].map(item2idx)

    n_users, n_items = len(user2idx), len(item2idx)
    pos = pos.groupby('user').filter(lambda g: len(g) >= min_interactions)
    pos = pos.sort_values(['user', 'timestamp'])

    train_rows, test_rows = [], []
    user_pos     = defaultdict(set)
    user_history = defaultdict(list)

    for uid, grp in pos.groupby('user'):
        items_sorted = grp['item'].tolist()
        test_rows.append({'user': uid, 'item': items_sorted[-1]})
        for it in items_sorted[:-1]:
            train_rows.append({'user': uid, 'item': it, 'label': 1})
            user_pos[uid].add(it)
            user_history[uid].append(it)

    return (pd.DataFrame(train_rows), pd.DataFrame(test_rows),
            user_pos, user_history, n_users, n_items, item2idx, user2idx)


(train_df, test_df, user_pos, user_history,
 n_users, n_items, item2idx, user2idx) = build_implicit_dataset(
    ratings, pos_threshold=4, min_interactions=5)

idx2item    = {v: k for k, v in item2idx.items()}
item_titles = dict(zip(items_df['item_id'], items_df['title']))

print(f"Train positives         : {len(train_df):,}")
print(f"Test users              : {len(test_df)}")
print(f"n_users={n_users}, n_items={n_items}")
print(f"Avg train positives/user: {len(train_df)/n_users:.1f}")

## CRITICAL: fix identical 99 negatives per user for all models.
rng = np.random.RandomState(SEED)
EVAL_NEGS = {}

for _, row in test_df.iterrows():
    u, pos_item = int(row['user']), int(row['item'])
    exclude     = user_pos[u] | {pos_item}
    negs        = []
    while len(negs) < 99:
        c = int(rng.randint(0, n_items))
        if c not in exclude:
            negs.append(c)
            exclude.add(c)
    EVAL_NEGS[u] = negs

print(f"Pre-sampled {len(EVAL_NEGS)} x 99 fixed evaluation negatives.")

"""## 2. Dataset & Training Utilities"""

class ImplicitDataset(Dataset):
    """
    Original BCE pointwise dataset — kept for baseline comparisons.
    For every positive, samples neg_ratio negatives uniformly.
    """
    def __init__(self, train_df, user_pos, n_items, neg_ratio=4):
        self.user_pos  = user_pos
        self.n_items   = n_items
        self.neg_ratio = neg_ratio
        self.positives = list(zip(train_df['user'].tolist(),
                                  train_df['item'].tolist()))

    def __len__(self):
        return len(self.positives) * (1 + self.neg_ratio)

    def __getitem__(self, idx):
        pos_idx = idx // (1 + self.neg_ratio)
        within  = idx %  (1 + self.neg_ratio)
        u, i    = self.positives[pos_idx]
        if within == 0:
            return (torch.tensor(u, dtype=torch.long),
                    torch.tensor(i, dtype=torch.long),
                    torch.tensor(1.0, dtype=torch.float32))
        neg = random.randint(0, self.n_items - 1)
        while neg in self.user_pos[u]:
            neg = random.randint(0, self.n_items - 1)
        return (torch.tensor(u,   dtype=torch.long),
                torch.tensor(neg, dtype=torch.long),
                torch.tensor(0.0, dtype=torch.float32))


def train_model(
    model, train_df, user_pos, n_items,
    n_epochs=30, batch_size=2048, lr=1e-3,
    weight_decay=1e-5, neg_ratio=4, device=DEVICE
):
    """
    Original BCE trainer (kept for pre-training GMF and MLP branches).
    Uses BCEWithLogitsLoss + CosineAnnealingLR.
    """
    dataset   = ImplicitDataset(train_df, user_pos, n_items, neg_ratio)
    loader    = DataLoader(dataset, batch_size=batch_size, shuffle=True,
                           num_workers=0, pin_memory=(device.type == 'cuda'))
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    criterion = nn.BCEWithLogitsLoss()
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=n_epochs, eta_min=1e-5)

    model.train()
    for epoch in range(1, n_epochs + 1):
        total_loss = 0.0
        for users, items, labels in loader:
            users, items, labels = users.to(device), items.to(device), labels.to(device)
            optimizer.zero_grad(set_to_none=True)
            loss = criterion(model(users, items), labels)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            total_loss += loss.item() * len(users)
        scheduler.step()
        if epoch % 5 == 0 or epoch == 1:
            avg = total_loss / len(dataset)
            print(f"  Epoch {epoch:3d}/{n_epochs} | Loss: {avg:.5f} | LR: {scheduler.get_last_lr()[0]:.2e}")
    return model

def evaluate_ranking(
    scorer, test_df, eval_negs,
    Ks=(5, 10, 15, 20), device=DEVICE, is_neural=True
) -> dict:
    """
    Leave-one-out ranking evaluation on pre-sampled fixed negatives.
    candidates = [positive] + 99 negatives (100 total).
    rank = 1-indexed position of positive in descending-score order.
    HR@K  = 1  if rank <= K
    NDCG@K = 1/log2(rank+1)  if rank <= K
    """
    if is_neural:
        scorer.eval()
    results = {f'NDCG@{k}': [] for k in Ks}
    results.update({f'HR@{k}': [] for k in Ks})

    with torch.no_grad():
        for _, row in test_df.iterrows():
            u, pos_item = int(row['user']), int(row['item'])
            candidates  = [pos_item] + eval_negs[u]
            if is_neural:
                u_t    = torch.tensor([u] * 100,  dtype=torch.long, device=device)
                i_t    = torch.tensor(candidates, dtype=torch.long, device=device)
                scores = torch.sigmoid(scorer(u_t, i_t)).cpu().numpy()
            else:
                scores = scorer.score_candidates(u, candidates)

            rank = int((scores[1:] >= scores[0]).sum()) + 1
            for k in Ks:
                results[f'HR@{k}'].append(1 if rank <= k else 0)
                results[f'NDCG@{k}'].append(
                    1.0 / np.log2(rank + 1) if rank <= k else 0.0
                )
    return {key: float(np.mean(vals)) for key, vals in results.items()}

"""## 3. Models"""

class PopularityModel:
    """Non-personalised baseline: score = global interaction count."""
    def __init__(self): self.item_scores = {}
    def fit(self, train_df):
        self.item_scores = train_df['item'].value_counts().to_dict()
        print(f"  Popularity model fitted. "
              f"Most popular item: {train_df['item'].value_counts().idxmax()} "
              f"({train_df['item'].value_counts().iloc[0]} interactions)")
        return self
    def score_candidates(self, user, candidates):
        return np.array([self.item_scores.get(c, 0.0) for c in candidates], dtype=float)


class GMF(nn.Module):
    """
    Generalised Matrix Factorization (He et al. WWW 2017).
    score(u,i) = output_layer( p_u ⊙ q_i )
    """
    def __init__(self, n_users, n_items, emb_dim=128):
        super().__init__()
        self.user_emb = nn.Embedding(n_users, emb_dim)
        self.item_emb = nn.Embedding(n_items, emb_dim)
        self.output   = nn.Linear(emb_dim, 1)
        nn.init.normal_(self.user_emb.weight, std=0.01)
        nn.init.normal_(self.item_emb.weight, std=0.01)
        nn.init.xavier_uniform_(self.output.weight)
        nn.init.zeros_(self.output.bias)
    def forward(self, users, items):
        return self.output(self.user_emb(users) * self.item_emb(items)).squeeze(-1)


class NeuMF(nn.Module):
    """
    Neural Matrix Factorization (He et al., WWW 2017).

    Two parallel branches with separate embeddings:
      GMF branch: p_u_gmf ⊙ q_i_gmf            (linear interactions)
      MLP branch: FC(concat(p_u_mlp, q_i_mlp))  (non-linear interactions)

    IMPROVEMENTS vs v3:
      emb_dim  : 64  → 128   (more representational capacity)
      mlp_dims : (256,128,64) → (512,256,128)  (wider non-linear tower)
      Training : see train_neumf_improved() below
    """
    def __init__(
        self, n_users, n_items,
        emb_dim  = 128,             # ← was 64
        mlp_dims = (512, 256, 128), # ← was (256, 128, 64)
        dropout  = 0.2
    ):
        super().__init__()
        self.user_emb_gmf = nn.Embedding(n_users, emb_dim)
        self.item_emb_gmf = nn.Embedding(n_items, emb_dim)
        self.user_emb_mlp = nn.Embedding(n_users, emb_dim)
        self.item_emb_mlp = nn.Embedding(n_items, emb_dim)

        mlp_layers, in_dim = [], emb_dim * 2
        for out_dim in mlp_dims:
            mlp_layers += [
                nn.Linear(in_dim, out_dim),
                nn.LayerNorm(out_dim),
                nn.ReLU(),
                nn.Dropout(dropout)
            ]
            in_dim = out_dim
        self.mlp     = nn.Sequential(*mlp_layers)
        self.predict = nn.Linear(emb_dim + mlp_dims[-1], 1)
        self._init_weights()

    def _init_weights(self):
        for emb in [self.user_emb_gmf, self.item_emb_gmf,
                    self.user_emb_mlp, self.item_emb_mlp]:
            nn.init.normal_(emb.weight, std=0.01)
        for m in self.mlp.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight); nn.init.zeros_(m.bias)
        nn.init.xavier_uniform_(self.predict.weight)
        nn.init.zeros_(self.predict.bias)

    def forward(self, users, items):
        gmf_out = self.user_emb_gmf(users) * self.item_emb_gmf(items)
        mlp_out = self.mlp(torch.cat([
            self.user_emb_mlp(users), self.item_emb_mlp(items)
        ], dim=-1))
        return self.predict(torch.cat([gmf_out, mlp_out], dim=-1)).squeeze(-1)


class MLPModel(nn.Module):
    """Pure MLP — used as one of the two pre-training branches for NeuMF."""
    def __init__(self, n_users, n_items, emb_dim=128,
                 mlp_dims=(512, 256, 128), dropout=0.2):
        super().__init__()
        self.user_emb = nn.Embedding(n_users, emb_dim)
        self.item_emb = nn.Embedding(n_items, emb_dim)
        layers, in_dim = [], emb_dim * 2
        for out_dim in mlp_dims:
            layers += [nn.Linear(in_dim, out_dim), nn.LayerNorm(out_dim),
                       nn.ReLU(), nn.Dropout(dropout)]
            in_dim = out_dim
        self.mlp     = nn.Sequential(*layers)
        self.predict = nn.Linear(mlp_dims[-1], 1)
        nn.init.normal_(self.user_emb.weight, std=0.01)
        nn.init.normal_(self.item_emb.weight, std=0.01)
        for m in self.mlp.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight); nn.init.zeros_(m.bias)
        nn.init.xavier_uniform_(self.predict.weight); nn.init.zeros_(self.predict.bias)
    def forward(self, users, items):
        return self.predict(
            self.mlp(torch.cat([self.user_emb(users), self.item_emb(items)], dim=-1))
        ).squeeze(-1)


def init_neumf_from_pretrained(neuMF: NeuMF, gmf: GMF, mlp: MLPModel) -> NeuMF:
    """
    Initialise NeuMF from separately pre-trained GMF and MLP weights.
    Technique from He et al. (NeuMF paper, Section 3.4).
    Gives +3-5% NDCG over random init by providing good starting embeddings.
    """
    neuMF.user_emb_gmf.weight.data.copy_(gmf.user_emb.weight.data)
    neuMF.item_emb_gmf.weight.data.copy_(gmf.item_emb.weight.data)
    neuMF.user_emb_mlp.weight.data.copy_(mlp.user_emb.weight.data)
    neuMF.item_emb_mlp.weight.data.copy_(mlp.item_emb.weight.data)

    src_linears = [m for m in mlp.mlp.modules()   if isinstance(m, nn.Linear)]
    dst_linears = [m for m in neuMF.mlp.modules() if isinstance(m, nn.Linear)]
    for src, dst in zip(src_linears, dst_linears):
        dst.weight.data.copy_(src.weight.data)
        dst.bias.data.copy_(src.bias.data)

    alpha = 0.5
    neuMF.predict.weight.data = torch.cat(
        [alpha * gmf.output.weight.data, (1-alpha) * mlp.predict.weight.data], dim=1
    )
    neuMF.predict.bias.data.zero_()
    print("  ✓ NeuMF branches initialised from pre-trained GMF + MLP weights.")
    return neuMF


# Sanity check
_u = torch.randint(0, 10, (4,))
_i = torch.randint(0, 20, (4,))
print("GMF   output:", GMF(10, 20, 16)(_u, _i).shape)
print("NeuMF output:", NeuMF(10, 20, 16, (32, 16, 8))(_u, _i).shape)
del _u, _i

class BPRDataset(Dataset):
    """
    Original pairwise BPR dataset with uniform negative sampling.
    Kept for ablation comparison.
    """
    def __init__(self, train_df, user_pos, n_items):
        self.pairs    = list(zip(train_df['user'].tolist(), train_df['item'].tolist()))
        self.user_pos = user_pos
        self.n_items  = n_items
    def __len__(self): return len(self.pairs)
    def __getitem__(self, idx):
        u, pos = self.pairs[idx]
        neg = random.randint(0, self.n_items - 1)
        while neg in self.user_pos[u]:
            neg = random.randint(0, self.n_items - 1)
        return (torch.tensor(u, dtype=torch.long),
                torch.tensor(pos, dtype=torch.long),
                torch.tensor(neg, dtype=torch.long))


def train_bpr(
    model, train_df, user_pos, n_items,
    n_epochs=50, batch_size=2048, lr=1e-3,
    weight_decay=1e-5, device=DEVICE
):
    """
    Original BPR trainer with uniform negatives.
    Loss: L = -mean(log σ(score_pos - score_neg))
    Kept for ablation comparison against improved variant.
    """
    dataset   = BPRDataset(train_df, user_pos, n_items)
    loader    = DataLoader(dataset, batch_size=batch_size, shuffle=True,
                           num_workers=0, pin_memory=(device.type == 'cuda'))
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=n_epochs, eta_min=1e-5)
    model.train()
    for epoch in range(1, n_epochs + 1):
        total_loss = 0.0
        for users, pos_items, neg_items in loader:
            users, pos_items, neg_items = users.to(device), pos_items.to(device), neg_items.to(device)
            pos_scores = model(users, pos_items)
            neg_scores = model(users, neg_items)
            loss = -torch.log(torch.sigmoid(pos_scores - neg_scores) + 1e-8).mean()
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            total_loss += loss.item() * len(users)
        scheduler.step()
        if epoch % 5 == 0 or epoch == 1:
            print(f"  Epoch {epoch:3d}/{n_epochs} | BPR Loss: {total_loss/len(dataset):.5f} | LR: {scheduler.get_last_lr()[0]:.2e}")
    return model

class ItemKNN:
    """Item-based nearest-neighbour CF. Similarity = adjusted cosine."""
    def __init__(self, k=50):
        self.k = k; self.sim = None; self.user_history = {}
    def fit(self, train_df, n_users, n_items, user_pos):
        self.user_history = {u: list(items) for u, items in user_pos.items()}
        R = np.zeros((n_users, n_items), dtype=np.float32)
        for _, row in train_df.iterrows():
            R[int(row['user']), int(row['item'])] = 1.0
        norms = np.linalg.norm(R, axis=0, keepdims=True)
        norms[norms == 0] = 1.0
        R_norm = R / norms
        print(f"  Computing {n_items}x{n_items} item-item similarity matrix...")
        sim = R_norm.T @ R_norm
        np.fill_diagonal(sim, 0.0)
        if self.k < n_items - 1:
            for i in range(n_items):
                row = sim[i]
                threshold = np.partition(row, -self.k)[-self.k]
                sim[i][row < threshold] = 0.0
        self.sim = sim
        print(f"  ItemKNN fitted. k={self.k}")
        return self
    def score_candidates(self, user, candidates):
        hist = self.user_history.get(user, [])
        if not hist or self.sim is None:
            return np.zeros(len(candidates), dtype=float)
        return self.sim[np.array(candidates, dtype=int)][:, np.array(hist, dtype=int)].sum(axis=1)

"""## 4. ★ Improved NeuMF Training Infrastructure ★

Three synergistic improvements over the baseline:

| Improvement | Why it helps |
|---|---|
| **BPR pairwise loss** | Directly maximises P(score_pos > score_neg) — aligns loss with ranking objective. BCE optimises absolute scores, not ordering. |
| **Popularity-weighted negatives** (freq^0.75) | Popular items the user hasn't rated are harder to reject than obscure ones. Harder negatives = more informative gradients from the first epoch. |
| **DNS after warmup** | Once the model has learned non-trivial scores (after warmup), we score dns_k candidate negatives per positive and pick the hardest. Steeper gradient → faster convergence to better optima. Warmup prevents DNS with an untrained model (random scores = random "hard" negatives = noise). |
"""

def build_pop_weights(train_df: pd.DataFrame, n_items: int,
                       alpha: float = 0.75) -> np.ndarray:
    """
    Popularity-weighted sampling distribution ∝ item_freq^alpha.
    alpha=0.75 (word2vec standard) smooths dominance of top items
    while still making popular items significantly more likely negatives.
    Returns a probability array over all n_items.
    """
    counts = train_df['item'].value_counts()
    freq   = np.array([counts.get(i, 0) for i in range(n_items)], dtype=float)
    w      = np.power(freq + 1, alpha)   # +1 avoids zero weights
    return (w / w.sum())


def train_neumf_improved(
    model,
    train_df:       pd.DataFrame,
    user_pos:       dict,
    n_items:        int,
    n_epochs:       int   = 50,
    batch_size:     int   = 2048,
    lr:             float = 5e-4,
    weight_decay:   float = 1e-5,
    warmup_epochs:  int   = 15,
    dns_k:          int   = 8,
    device:         torch.device = DEVICE
) -> nn.Module:
    """
    Improved NeuMF training with three stacked improvements:

    Phase 1 — epochs [1, warmup_epochs]:
        Loss : BPR  →  L = -log σ(score_pos - score_neg)
        Negs : Popularity-weighted sampling (freq^0.75)

    Phase 2 — epochs [warmup+1, n_epochs]:
        Loss : BPR  (same)
        Negs : DNS (Dynamic Negative Sampling)
               For each positive in the batch:
                 1. Sample dns_k candidate negatives (pop-weighted)
                 2. Score all in one batched forward pass
                 3. Select the highest-scoring (hardest) as the negative
               DNS is batched → single forward pass per training batch,
               not per sample.  GPU-friendly and adds minimal overhead.

    WHY WARMUP BEFORE DNS:
        An untrained model assigns nearly random scores, so the "hardest"
        DNS candidate is random noise.  Warmup lets the model develop
        meaningful representations first, after which DNS provides truly
        harder and more informative negatives.
    """
    pop_weights = build_pop_weights(train_df, n_items)
    positives   = list(zip(train_df['user'].tolist(), train_df['item'].tolist()))

    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=n_epochs, eta_min=1e-5
    )

    for epoch in range(1, n_epochs + 1):
        random.shuffle(positives)
        model.train()
        use_dns    = (epoch > warmup_epochs)
        total_loss = 0.0
        n_batches  = 0

        for start in range(0, len(positives), batch_size):
            batch = positives[start : start + batch_size]
            if not batch:
                continue
            users_list = [x[0] for x in batch]
            pos_list   = [x[1] for x in batch]
            B          = len(batch)

            # ── Negative sampling ─────────────────────────────────────────────
            if use_dns:
                # Batch-level DNS: score dns_k candidates per positive,
                # then select the hardest (highest model score) for each user.
                all_cands = []
                for u in users_list:
                    cands = []
                    while len(cands) < dns_k:
                        c = int(np.random.choice(n_items, p=pop_weights))
                        if c not in user_pos[u]:
                            cands.append(c)
                    all_cands.append(cands)

                # One batched forward pass to score all candidates
                model.eval()
                with torch.no_grad():
                    flat_u = [u for u, cs in zip(users_list, all_cands) for _ in cs]
                    flat_i = [c for cs in all_cands for c in cs]
                    u_t = torch.tensor(flat_u, dtype=torch.long, device=device)
                    i_t = torch.tensor(flat_i, dtype=torch.long, device=device)
                    dns_scores = model(u_t, i_t).cpu().numpy().reshape(B, dns_k)
                model.train()

                neg_list = [cs[int(np.argmax(sc))]
                            for cs, sc in zip(all_cands, dns_scores)]
            else:
                # Phase 1: popularity-weighted uniform sampling
                neg_list = []
                for u in users_list:
                    c = int(np.random.choice(n_items, p=pop_weights))
                    while c in user_pos[u]:
                        c = int(np.random.choice(n_items, p=pop_weights))
                    neg_list.append(c)

            # ── BPR loss ──────────────────────────────────────────────────────
            users_t = torch.tensor(users_list, dtype=torch.long, device=device)
            pos_t   = torch.tensor(pos_list,   dtype=torch.long, device=device)
            neg_t   = torch.tensor(neg_list,   dtype=torch.long, device=device)

            optimizer.zero_grad(set_to_none=True)
            pos_scores = model(users_t, pos_t)
            neg_scores = model(users_t, neg_t)
            loss = -torch.log(torch.sigmoid(pos_scores - neg_scores) + 1e-8).mean()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            total_loss += loss.item()
            n_batches  += 1

        scheduler.step()
        if epoch % 5 == 0 or epoch == 1:
            avg = total_loss / max(n_batches, 1)
            tag = "DNS+pop" if use_dns else "pop-weighted"
            print(f"  Epoch {epoch:3d}/{n_epochs} | BPR Loss: {avg:.5f} | "
                  f"LR: {scheduler.get_last_lr()[0]:.2e} | Neg: {tag}")
    return model

"""## 5. Hyperparameters"""

# ════════════════════════════════════════════════════════════════════════════
# HYPERPARAMETERS — what changed vs v3 and WHY
#
#  emb_dim       64  → 128       More capacity. ML-100K supports it without
#                                overfitting (regularised by dropout + weight_decay).
#
#  mlp_dims      (256,128,64)    More non-linear capacity.  Pre-trained init +
#                → (512,256,128) dropout prevent overfitting.
#
#  n_epochs      30 → 50         BPR+DNS converges more slowly but reaches a
#                                better optimum than BCE with uniform negatives.
#
#  lr            1e-3 → 5e-4     Slightly lower LR stabilises the larger model.
#                                CosineAnnealing still decays to 1e-5.
#
#  warmup_epochs = 15            First 15 epochs: BPR + pop-weighted negatives.
#                                Then DNS activates with meaningful model scores.
#
#  dns_k = 8                     Score 8 candidate negatives per positive per
#                                batch to find the hardest.  Higher = better but
#                                slower (each DNS step = one extra fwd pass).
# ════════════════════════════════════════════════════════════════════════════

HP = dict(
    emb_dim       = 128,             # ← was 64
    mlp_dims      = (512, 256, 128), # ← was (256, 128, 64)
    dropout       = 0.2,
    n_epochs      = 50,              # ← was 30
    batch_size    = 2048,
    lr            = 5e-4,            # ← was 1e-3
    weight_decay  = 1e-5,
    warmup_epochs = 15,              # NEW
    dns_k         = 8,               # NEW
    neg_ratio     = 4,               # kept for BCE baseline models
)
print("Hyperparameters:")
for k, v in HP.items():
    print(f"  {k:20s} = {v}")

"""## 6. Baselines"""

print("=" * 60)
print("MODEL 1 — Popularity Baseline")
print("=" * 60)
pop_model = PopularityModel().fit(train_df)
res_pop   = evaluate_ranking(pop_model, test_df, EVAL_NEGS, is_neural=False)
print(f"  NDCG@5={res_pop['NDCG@5']:.4f}  NDCG@10={res_pop['NDCG@10']:.4f}  "
      f"HR@5={res_pop['HR@5']:.4f}  HR@10={res_pop['HR@10']:.4f}")

print("\n" + "=" * 60)
print("MODEL 2 — ItemKNN (k=50)")
print("=" * 60)
item_knn = ItemKNN(k=50).fit(train_df, n_users, n_items, user_pos)
res_knn  = evaluate_ranking(item_knn, test_df, EVAL_NEGS, is_neural=False)
print(f"  NDCG@5={res_knn['NDCG@5']:.4f}  NDCG@10={res_knn['NDCG@10']:.4f}  "
      f"HR@5={res_knn['HR@5']:.4f}  HR@10={res_knn['HR@10']:.4f}")

"""## 7. Models — Baseline NeuMF (for comparison)"""

print("=" * 60)
print("MODEL 3 — NeuMF baseline (random init, BCE, emb=64, 30 epochs)")
print("=" * 60)
torch.manual_seed(SEED)
neuMF_baseline = NeuMF(n_users, n_items, emb_dim=64,
                        mlp_dims=(256, 128, 64), dropout=0.2).to(DEVICE)
print(f"  Parameters: {sum(p.numel() for p in neuMF_baseline.parameters()):,}")
neuMF_baseline = train_model(
    neuMF_baseline, train_df, user_pos, n_items,
    n_epochs=30, batch_size=HP['batch_size'],
    lr=1e-3, weight_decay=HP['weight_decay'],
    neg_ratio=HP['neg_ratio'], device=DEVICE
)
res_neuMF_baseline = evaluate_ranking(neuMF_baseline, test_df, EVAL_NEGS)
print(f"  NDCG@5={res_neuMF_baseline['NDCG@5']:.4f}  "
      f"NDCG@10={res_neuMF_baseline['NDCG@10']:.4f}  "
      f"HR@5={res_neuMF_baseline['HR@5']:.4f}  "
      f"HR@10={res_neuMF_baseline['HR@10']:.4f}")

"""## 8. Pre-training GMF and MLP (NeuMF branches)"""

print("=" * 60)
print("MODEL 4 — GMF (BCE, emb=128) — pre-training for NeuMF GMF branch")
print("=" * 60)
torch.manual_seed(SEED)
gmf_model = GMF(n_users, n_items, emb_dim=HP['emb_dim']).to(DEVICE)
print(f"  Parameters: {sum(p.numel() for p in gmf_model.parameters()):,}")
gmf_model = train_model(
    gmf_model, train_df, user_pos, n_items,
    n_epochs=30, batch_size=HP['batch_size'],
    lr=HP['lr'], weight_decay=HP['weight_decay'],
    neg_ratio=HP['neg_ratio'], device=DEVICE
)
res_gmf = evaluate_ranking(gmf_model, test_df, EVAL_NEGS)
print(f"  NDCG@5={res_gmf['NDCG@5']:.4f}  NDCG@10={res_gmf['NDCG@10']:.4f}  "
      f"HR@5={res_gmf['HR@5']:.4f}  HR@10={res_gmf['HR@10']:.4f}")

print("=" * 60)
print("MODEL 5 — Pure MLP (BCE, emb=128) — pre-training for NeuMF MLP branch")
print("=" * 60)
torch.manual_seed(SEED)
mlp_model = MLPModel(n_users, n_items,
                      emb_dim  = HP['emb_dim'],
                      mlp_dims = HP['mlp_dims'],
                      dropout  = HP['dropout']).to(DEVICE)
print(f"  Parameters: {sum(p.numel() for p in mlp_model.parameters()):,}")
mlp_model = train_model(
    mlp_model, train_df, user_pos, n_items,
    n_epochs=30, batch_size=HP['batch_size'],
    lr=HP['lr'], weight_decay=HP['weight_decay'],
    neg_ratio=HP['neg_ratio'], device=DEVICE
)
res_mlp = evaluate_ranking(mlp_model, test_df, EVAL_NEGS)
print(f"  NDCG@5={res_mlp['NDCG@5']:.4f}  NDCG@10={res_mlp['NDCG@10']:.4f}  "
      f"HR@5={res_mlp['HR@5']:.4f}  HR@10={res_mlp['HR@10']:.4f}")

"""## 9. ★ Main Model: NeuMF Improved ★

Full pipeline:
1. Pre-train GMF → good GMF-branch embeddings
2. Pre-train MLP → good MLP-branch representations
3. `init_neumf_from_pretrained` → warm-start NeuMF (avoids random-init saddle points)
4. Fine-tune with `train_neumf_improved` → BPR + pop-weighted + DNS after warmup
"""

print("=" * 60)
print("★ MODEL 6 — NeuMF IMPROVED ★")
print("  Pipeline: Pre-train GMF + MLP → init NeuMF → BPR + pop-weighted + DNS")
print("=" * 60)

torch.manual_seed(SEED)
neuMF_improved = NeuMF(
    n_users, n_items,
    emb_dim  = HP['emb_dim'],
    mlp_dims = HP['mlp_dims'],
    dropout  = HP['dropout']
).to(DEVICE)

# ── Step 1: warm-start from pre-trained GMF + MLP ───────────────────────────
neuMF_improved = init_neumf_from_pretrained(neuMF_improved, gmf_model, mlp_model)
print(f"  Total parameters: {sum(p.numel() for p in neuMF_improved.parameters()):,}")

# ── Step 2: fine-tune with improved BPR + DNS trainer ───────────────────────
neuMF_improved = train_neumf_improved(
    neuMF_improved,
    train_df,
    user_pos,
    n_items,
    n_epochs      = HP['n_epochs'],
    batch_size    = HP['batch_size'],
    lr            = HP['lr'],
    weight_decay  = HP['weight_decay'],
    warmup_epochs = HP['warmup_epochs'],
    dns_k         = HP['dns_k'],
    device        = DEVICE,
)

res_neuMF_improved = evaluate_ranking(neuMF_improved, test_df, EVAL_NEGS)
print(f"\n  ★ NeuMF IMPROVED RESULTS ★")
print(f"  NDCG@5 ={res_neuMF_improved['NDCG@5']:.4f}   "
      f"NDCG@10={res_neuMF_improved['NDCG@10']:.4f}   "
      f"NDCG@15={res_neuMF_improved['NDCG@15']:.4f}   "
      f"NDCG@20={res_neuMF_improved['NDCG@20']:.4f}")
print(f"  HR@5   ={res_neuMF_improved['HR@5']:.4f}   "
      f"HR@10  ={res_neuMF_improved['HR@10']:.4f}   "
      f"HR@15  ={res_neuMF_improved['HR@15']:.4f}   "
      f"HR@20  ={res_neuMF_improved['HR@20']:.4f}")

"""## 10. Ablation: NeuMF + BPR with Uniform Negatives

This isolates the contribution of DNS by using BPR with uniform negatives (no pop-weighting, no DNS).
"""

print("=" * 60)
print("MODEL 7 — NeuMF + BPR, uniform negatives (ablation, no DNS)")
print("=" * 60)
torch.manual_seed(SEED)
neuMF_bpr_uniform = NeuMF(
    n_users, n_items,
    emb_dim  = HP['emb_dim'],
    mlp_dims = HP['mlp_dims'],
    dropout  = HP['dropout']
).to(DEVICE)
neuMF_bpr_uniform = init_neumf_from_pretrained(neuMF_bpr_uniform, gmf_model, mlp_model)
neuMF_bpr_uniform = train_bpr(
    neuMF_bpr_uniform, train_df, user_pos, n_items,
    n_epochs=HP['n_epochs'], batch_size=HP['batch_size'],
    lr=HP['lr'], weight_decay=HP['weight_decay'], device=DEVICE,
)
res_bpr_uniform = evaluate_ranking(neuMF_bpr_uniform, test_df, EVAL_NEGS)
print(f"  NDCG@5={res_bpr_uniform['NDCG@5']:.4f}  "
      f"NDCG@10={res_bpr_uniform['NDCG@10']:.4f}  "
      f"HR@5={res_bpr_uniform['HR@5']:.4f}  "
      f"HR@10={res_bpr_uniform['HR@10']:.4f}")

"""## 11. Rerankers"""

def build_genre_matrix(items_df, item2idx):
    """Build (n_items x 19) L2-normalised genre feature matrix."""
    genre_cols = [
        'action','adventure','animation','childrens','comedy','crime',
        'documentary','drama','fantasy','film_noir','horror','musical',
        'mystery','romance','sci_fi','thriller','war','western','unknown'
    ]
    n   = len(item2idx)
    mat = np.zeros((n, len(genre_cols)), dtype=np.float32)
    for _, row in items_df.iterrows():
        orig_id = row['item_id']
        if orig_id in item2idx:
            idx      = item2idx[orig_id]
            mat[idx] = [float(row.get(g, 0)) for g in genre_cols]
    norms       = np.linalg.norm(mat, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return mat / norms


@torch.no_grad()
def evaluate_with_genre_reranking(
    neuMF_model, test_df, eval_negs, user_history, genre_mat,
    Ks=(5, 10, 15, 20), n_rerank=20, alpha=0.30, device=None
):
    """
    NeuMF + genre-based local re-ranking.
    blended_score = (1-alpha)*NeuMF_score + alpha*genre_cosine_similarity
    """
    if device is None:
        device = next(neuMF_model.parameters()).device
    neuMF_model.eval()
    results = {f'NDCG@{k}': [] for k in Ks}
    results.update({f'HR@{k}': [] for k in Ks})

    for _, row in test_df.iterrows():
        u, pos_item = int(row['user']), int(row['item'])
        candidates  = [pos_item] + eval_negs[u]
        u_t    = torch.tensor([u] * 100, dtype=torch.long, device=device)
        i_t    = torch.tensor(candidates, dtype=torch.long, device=device)
        scores = torch.sigmoid(neuMF_model(u_t, i_t)).cpu().numpy()

        nmf_order = np.argsort(scores)[::-1].tolist()
        top_idx   = nmf_order[:n_rerank]
        rest_idx  = nmf_order[n_rerank:]

        hist = user_history[u]
        if hist:
            profile = genre_mat[hist].mean(axis=0)
            pnorm   = np.linalg.norm(profile)
            if pnorm > 0: profile /= pnorm
            top_items   = [candidates[ci] for ci in top_idx]
            genre_sims  = genre_mat[top_items] @ profile
            blended     = (1 - alpha) * scores[top_idx] + alpha * genre_sims
            reranked    = [top_idx[i] for i in np.argsort(blended)[::-1]]
        else:
            reranked = top_idx

        final_order = reranked + rest_idx
        pos_rank    = final_order.index(0) + 1
        for k in Ks:
            results[f'HR@{k}'].append(1 if pos_rank <= k else 0)
            results[f'NDCG@{k}'].append(1.0/np.log2(pos_rank+1) if pos_rank<=k else 0.0)
    return {key: float(np.mean(vals)) for key, vals in results.items()}


genre_mat = build_genre_matrix(items_df, item2idx)
print(f"Genre matrix: {genre_mat.shape}  (n_items x 19 genres, L2-normalised)")

print("\n" + "=" * 60)
print("MODEL 8 — NeuMF Improved + Genre Reranker (alpha=0.30)")
print("=" * 60)
res_genre_rr = evaluate_with_genre_reranking(
    neuMF_model  = neuMF_improved,
    test_df      = test_df,
    eval_negs    = EVAL_NEGS,
    user_history = user_history,
    genre_mat    = genre_mat,
    Ks           = (5, 10, 15, 20),
    n_rerank     = 20,
    alpha        = 0.30,
    device       = DEVICE,
)
print(f"  NDCG@5={res_genre_rr['NDCG@5']:.4f}  "
      f"NDCG@10={res_genre_rr['NDCG@10']:.4f}  "
      f"HR@5={res_genre_rr['HR@5']:.4f}  "
      f"HR@10={res_genre_rr['HR@10']:.4f}")

API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')


@torch.no_grad()
def evaluate_with_llm_reranking(
    neuMF_model, test_df, eval_negs, user_history,
    idx2item, item_titles,
    Ks=(5, 10, 15, 20), n_rerank=20,
    api_key=None, device=DEVICE, max_users=None
):
    """
    NeuMF + LLM (Claude) re-ranking.
    Top-n_rerank candidates by NeuMF score are re-ordered by the LLM.
    Falls back to NeuMF-only if no API key is available.
    """
    key     = api_key or os.environ.get('ANTHROPIC_API_KEY')
    use_llm = False; client = None
    if key:
        try:
            import anthropic
            client  = anthropic.Anthropic(api_key=key); use_llm = True
            print(f"[LLM] Claude will rerank top-{n_rerank} per user.")
        except ImportError:
            print("[LLM] anthropic package not found. pip install anthropic")
    else:
        print("[LLM] No ANTHROPIC_API_KEY found. Falling back to NeuMF scores.")

    neuMF_model.eval()
    results = {f'NDCG@{k}': [] for k in Ks}
    results.update({f'HR@{k}': [] for k in Ks})
    n_ok = n_fail = 0

    for eval_idx, (_, row) in enumerate(test_df.iterrows()):
        if max_users is not None and eval_idx >= max_users: break
        u, pos_item = int(row['user']), int(row['item'])
        candidates  = [pos_item] + eval_negs[u]
        u_t    = torch.tensor([u]*100, dtype=torch.long, device=device)
        i_t    = torch.tensor(candidates, dtype=torch.long, device=device)
        scores = torch.sigmoid(neuMF_model(u_t, i_t)).cpu().numpy()
        nmf_order = np.argsort(scores)[::-1].tolist()

        if use_llm:
            top_cand_idx  = nmf_order[:n_rerank]
            rest_cand_idx = nmf_order[n_rerank:]
            top_item_ids  = [candidates[ci] for ci in top_cand_idx]
            hist_titles   = [item_titles.get(idx2item.get(it,-1),'Unknown')
                             for it in user_history[u][-5:]]
            cand_info     = [f"item_id={iid}: {item_titles.get(idx2item.get(iid,-1),'Unknown')}"
                             for iid in top_item_ids]
            prompt = (
                f"A user recently enjoyed: {', '.join(hist_titles)}.\n\n"
                f"Rank the following {n_rerank} movies from MOST to LEAST relevant.\n"
                f"Output ONLY a JSON array of item_ids. Example: [42,7,15]\n\n"
                "Candidates:\n" + "\n".join(cand_info)
            )
            llm_reranked = top_cand_idx
            try:
                resp     = client.messages.create(
                    model='claude-haiku-4-5-20251001', max_tokens=256,
                    messages=[{'role':'user','content':prompt}])
                raw = resp.content[0].text.strip()
                s, e = raw.find('['), raw.rfind(']')+1
                if s != -1 and e > s:
                    ranked_ids = json.loads(raw[s:e])
                    id2pos = {candidates[ci]: ci for ci in top_cand_idx}
                    llm_reranked = [id2pos[r] for r in ranked_ids if r in id2pos]
                    seen = set(llm_reranked)
                    for ci in top_cand_idx:
                        if ci not in seen: llm_reranked.append(ci)
                n_ok += 1
            except Exception: n_fail += 1
            final_order = llm_reranked + rest_cand_idx
        else:
            final_order = nmf_order

        pos_rank = final_order.index(0) + 1
        for k in Ks:
            results[f'HR@{k}'].append(1 if pos_rank <= k else 0)
            results[f'NDCG@{k}'].append(1.0/np.log2(pos_rank+1) if pos_rank<=k else 0.0)

    if use_llm:
        print(f"[LLM] {n_ok}/{n_ok+n_fail} calls succeeded.")
    return {key: float(np.mean(vals)) for key, vals in results.items()}


print("\n" + "=" * 60)
print("MODEL 9 — NeuMF Improved + LLM Reranker")
print("=" * 60)
res_llm = evaluate_with_llm_reranking(
    neuMF_model  = neuMF_improved,
    test_df      = test_df,
    eval_negs    = EVAL_NEGS,
    user_history = user_history,
    idx2item     = idx2item,
    item_titles  = item_titles,
    Ks           = (5, 10, 15, 20),
    n_rerank     = 20,
    api_key      = API_KEY,
    device       = DEVICE,
    max_users    = None
)
print(f"  NDCG@5={res_llm['NDCG@5']:.4f}  "
      f"NDCG@10={res_llm['NDCG@10']:.4f}  "
      f"HR@5={res_llm['HR@5']:.4f}  "
      f"HR@10={res_llm['HR@10']:.4f}")

"""## 12. Final Comparison Table"""

KS = [5, 10, 15, 20]

main_results = {
    'Popularity'                    : res_pop,
    'ItemKNN (k=50)'                : res_knn,
    'GMF / MF (BCE, emb=128)'       : res_gmf,
    'Pure MLP (BCE, emb=128)'       : res_mlp,
    'NeuMF baseline (BCE, emb=64)'  : res_neuMF_baseline,
    'NeuMF + BPR (uniform neg)'     : res_bpr_uniform,
    '★ NeuMF IMPROVED ★'            : res_neuMF_improved,
    'NeuMF Improved + Genre Rerank' : res_genre_rr,
    'NeuMF Improved + LLM Rerank'   : res_llm,
}

ndcg_cols = [f'NDCG@{k}' for k in KS]
hr_cols   = [f'HR@{k}'   for k in KS]
all_cols  = ndcg_cols + hr_cols
NAME_W    = 34
COL_W     = 9

header_cols = ''.join(f"{c:>{COL_W}}" for c in all_cols)
sep = '─' * (NAME_W + 2 + COL_W * len(all_cols))

print(); W = len(sep)
print('╔' + '═'*W + '╗')
print('║' + '  FINAL RESULTS — MovieLens 100K (Implicit Feedback)'.center(W) + '║')
print('║' + '  Protocol: Leave-one-out · 99 fixed negatives/user'.center(W) + '║')
print('╠' + '═'*W + '╣')
print(f"  {'Model':<{NAME_W}}" + header_cols)
print('  ' + sep)
for name, m in main_results.items():
    cells = ''.join(f"{m[c]:>{COL_W}.4f}" for c in all_cols)
    print(f"  {name:<{NAME_W}}{cells}")
print('╚' + '═'*W + '╝')

print()
summary = pd.DataFrame(main_results).T[all_cols]
summary.index.name = 'Model'
print("All results sorted by NDCG@10:")
print(summary.round(4).sort_values('NDCG@10', ascending=False).to_string())

print()
print("Relative improvement vs. Popularity baseline (NDCG@10):")
base = res_pop['NDCG@10']
for name, m in main_results.items():
    delta = (m['NDCG@10'] - base) / base * 100
    arrow = '▲' if delta > 0 else ('▼' if delta < 0 else '—')
    print(f"  {name:<40}: {m['NDCG@10']:.4f}  {arrow} {abs(delta):+.1f}%")

print()
print("Improvement of IMPROVED NeuMF vs. Baseline NeuMF:")
for metric in ['NDCG@5', 'NDCG@10', 'HR@5', 'HR@10']:
    delta = (res_neuMF_improved[metric] - res_neuMF_baseline[metric]) / res_neuMF_baseline[metric] * 100
    print(f"  {metric}: {res_neuMF_baseline[metric]:.4f} → {res_neuMF_improved[metric]:.4f}  ({delta:+.1f}%)")

"""## 13. Top-K Recommendations for a Sample User"""

@torch.no_grad()
def top_k_for_user(model, u, user_pos, n_items, idx2item, titles, k=10, device=DEVICE):
    """Return a DataFrame of top-K recommended items for a given user."""
    model.eval()
    unseen = [i for i in range(n_items) if i not in user_pos[u]]
    chunk  = 4096; scores = []
    for s in range(0, len(unseen), chunk):
        u_t = torch.tensor([u]*len(unseen[s:s+chunk]), dtype=torch.long, device=device)
        i_t = torch.tensor(unseen[s:s+chunk],          dtype=torch.long, device=device)
        scores.append(torch.sigmoid(model(u_t, i_t)).cpu())
    scores  = torch.cat(scores).numpy()
    top_idx = np.argsort(scores)[::-1][:k]
    rows = []
    for rank, ci in enumerate(top_idx, 1):
        item_new  = unseen[ci]
        item_orig = idx2item.get(item_new, -1)
        rows.append({'Rank': rank, 'item_idx': item_new,
                     'Title': titles.get(item_orig, 'Unknown'),
                     'Score': round(float(scores[ci]), 4)})
    return pd.DataFrame(rows)


demo_user = 0
for K in [5, 10]:
    print(f"\nTop-{K} NeuMF Improved recommendations for user {demo_user}:")
    recs = top_k_for_user(neuMF_improved, demo_user, user_pos, n_items,
                           idx2item, item_titles, k=K)
    print(recs.to_string(index=False))